"""initial schema

Revision ID: e935de2c6a04
Revises: 
Create Date: 2026-04-16 21:21:29.039950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e935de2c6a04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_kind', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    op.create_index(op.f('ix_grant_compliance_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False, schema='grant_compliance')
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qb_employee_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qb_employee_id'),
    schema='grant_compliance'
    )
    op.create_table('funders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('funder_type', sa.Enum('federal', 'state', 'local', 'foundation', 'corporate', 'other', name='fundertype'), nullable=False),
    sa.Column('federal_pass_through', sa.Boolean(), nullable=False),
    sa.Column('cfda_number', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    op.create_table('qb_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qb_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qb_id'),
    schema='grant_compliance'
    )
    op.create_table('qb_classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qb_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qb_id'),
    schema='grant_compliance'
    )
    op.create_table('grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('funder_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('award_number', sa.String(length=100), nullable=True),
    sa.Column('qb_class_name', sa.String(length=255), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_award_cents', sa.BigInteger(), nullable=False),
    sa.Column('indirect_rate_pct', sa.Float(), nullable=True),
    sa.Column('indirect_rate_basis', sa.String(length=50), nullable=True),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funder_id'], ['grant_compliance.funders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    op.create_table('time_certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('splits', sa.JSON(), nullable=False),
    sa.Column('drafted_by', sa.String(length=100), nullable=False),
    sa.Column('drafted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('certified_by', sa.String(length=255), nullable=True),
    sa.Column('certified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_method', sa.String(length=50), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['grant_compliance.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qb_id', sa.String(length=50), nullable=False),
    sa.Column('qb_type', sa.String(length=50), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('qb_class_id', sa.String(length=36), nullable=True),
    sa.Column('qb_account_id', sa.String(length=36), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['qb_account_id'], ['grant_compliance.qb_accounts.id'], ),
    sa.ForeignKeyConstraint(['qb_class_id'], ['grant_compliance.qb_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qb_id'),
    schema='grant_compliance'
    )
    op.create_table('allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('budget_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', 'superseded', name='allocationstatus'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('proposed_by', sa.String(length=100), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grant_compliance.grants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['grant_compliance.transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    op.create_table('budget_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('budgeted_cents', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grant_compliance.grants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    op.create_table('report_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grant_compliance.grants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    op.create_table('compliance_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('allocation_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_citation', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'blocker', name='flagseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'waived', name='flagstatus'), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['grant_compliance.allocations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['grant_compliance.transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grant_compliance'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_flags', schema='grant_compliance')
    op.drop_table('report_drafts', schema='grant_compliance')
    op.drop_table('budget_lines', schema='grant_compliance')
    op.drop_table('allocations', schema='grant_compliance')
    op.drop_table('transactions', schema='grant_compliance')
    op.drop_table('time_certifications', schema='grant_compliance')
    op.drop_table('grants', schema='grant_compliance')
    op.drop_table('qb_classes', schema='grant_compliance')
    op.drop_table('qb_accounts', schema='grant_compliance')
    op.drop_table('funders', schema='grant_compliance')
    op.drop_table('employees', schema='grant_compliance')
    op.drop_index(op.f('ix_grant_compliance_audit_log_occurred_at'), table_name='audit_log', schema='grant_compliance')
    op.drop_table('audit_log', schema='grant_compliance')
    # ### end Alembic commands ###
